# Generated by Django 2.2.2 on 2020-11-15 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=1000)),
                ('content', models.CharField(blank=True, max_length=10000)),
                ('time', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_obj', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NewspaperString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newspaper_obj', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FlashUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmarked_articles', models.ManyToManyField(to='news.Article')),
                ('categories', models.ManyToManyField(to='news.CategoryString')),
                ('newspapers', models.ManyToManyField(to='news.NewspaperString')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
