# Generated by Django 2.2.2 on 2020-11-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashuser',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
