NEWS_SOURCES = {
    # "The Hindu": {
    #     "home": "https://www.thehindu.com/",
    #     "entertainment": "https://www.thehindu.com/entertainment/",
    #     "business": "https://www.thehindu.com/business/",
    #     "sports" : "https://www.thehindu.com/sport/",
    #     "world" : "https://www.thehindu.com/news/international/",
    #     "health" : "https://www.thehindu.com/life-and-style/",
    #     "technology" : "https://www.thehindu.com/sci-tech/technology/",
    #
    #
    # },
    "NDTV": {
        "home": "https://www.ndtv.com/world-news",
        "local": "https://www.ndtv.com/india",
        "entertainment": "https://www.ndtv.com/entertainment/",
        "health": "https://www.ndtv.com/health/",
        "technology": "https://www.ndtv.com/science",
        "business" : "https://www.ndtv.com/business/economy",
        "sports" : "https://www.ndtv.com/sports",
        "world" : "https://www.ndtv.com/world-news"
    },
    "Times of India": {
        "home": "https://timesofindia.indiatimes.com/briefs/world/",
        "local": "https://timesofindia.indiatimes.com/briefs/india/",
        "entertainment": "https://timesofindia.indiatimes.com/briefs/entertainment/",
        "business": "https://timesofindia.indiatimes.com/briefs/business/",
        "sports" : "https://timesofindia.indiatimes.com/briefs/sports/",
        "world" : "https://timesofindia.indiatimes.com/briefs/world/",
        "health" : "https://timesofindia.indiatimes.com/briefs/lifestyle/",
        "technology" : "https://timesofindia.indiatimes.com/briefs/gadgets/",
    },
    # "Hindustan Times": {
    #     "home": "https://www.hindustantimes.com/latest-news/page/?pageno={}",
    #     "local":"https://www.hindustantimes.com/cities/page/?pageno={}" ,
    #     "entertainment": "https://www.hindustantimes.com/entertainment/page/?pageno={}",
    #     "business": "https://www.hindustantimes.com/business-news/page/?pageno={}",
    #     "sports" : "https://www.hindustantimes.com/sports-newspage/?pageno={}/",
    #     "world" : "https://www.hindustantimes.com/world-news/page/?pageno={}",
    #     "health" : "https://www.hindustantimes.com/lifestyle/page/?pageno={}",
    #     "technology" : "https://www.hindustantimes.com/science/page/?pageno={}",
    # },
    # "Deccan Chronicle": {
    #     "home": "https://www.deccanchronicle.com/",
    #     "entertainment": "https://www.deccanchronicle.com/entertainment",
    #     "business": "https://www.deccanchronicle.com/business",
    #     "sports" : "https://www.deccanchronicle.com/sports",
    #     "world" : "https://www.deccanchronicle.com/world",
    #     "health" : "https://www.deccanchronicle.com/lifestyle",
    #     "technology" : "https://www.deccanchronicle.com/technology",
    # },
    "DD News": {
        "home": "http://ddnews.gov.in/international",
        "local": "http://ddnews.gov.in/national",
        "entertainment": "http://ddnews.gov.in/entertainment",
        "business": "http://ddnews.gov.in/business",
        "sports" : "http://ddnews.gov.in/sports",
        "world" : "http://ddnews.gov.in/international",
        "health" : "http://ddnews.gov.in/health",
        "technology" : "http://ddnews.gov.in/sci-tech",
    },
    "NEWS18": {
        "home": "https://www.news18.com/news/",
        "local": "https://www.news18.com/india/",
        "entertainment": "https://www.news18.com/movies/",
        "business": "https://www.news18.com/business/",
        "sports": "https://www.news18.com/sports/",
        "world": "https://www.news18.com/world/",
        "health": "https://www.news18.com/lifestyle/",
        "technology": "https://www.news18.com/tech/",
    },
    "Telegraph": {
        #"home": "https://www.telegraphindia.com/world/page-{}",
        #"local": "https://www.telegraphindia.com/india/page-{}",
        #"entertainment": "https://www.telegraphindia.com/entertainment/page-{}",
        #"business": "https://www.telegraphindia.com/business/page-{}",
        #"sports" : "https://www.telegraphindia.com/sports/page-{}",
        #"world" : "https://www.telegraphindia.com/world/page-{}",
        #"health" : "https://www.telegraphindia.com/health/page-{}",
        #"technology" : "https://www.telegraphindia.com/science-tech/page-{}",
        "home": "https://www.telegraphindia.com/world",
        "local": "https://www.telegraphindia.com/india",
        "entertainment": "https://www.telegraphindia.com/entertainment",
        "business": "https://www.telegraphindia.com/business",
        "sports" : "https://www.telegraphindia.com/sports",
        "world" : "https://www.telegraphindia.com/world",
        "health" : "https://www.telegraphindia.com/health",
        "technology" : "https://www.telegraphindia.com/science-tech",
    },
}